[build]
rustc-wrapper = "/opt/homebrew/bin/sccache"

[target.aarch64-apple-darwin]
rustflags = "-L /opt/homebrew/lib -L /opt/homebrew/opt/libpq/lib"

[target.x86_64-unknown-linux-musl]
rustflags = "-L /opt/homebrew/lib -L /opt/homebrew/opt/libpq/lib -C target-feature=+crt-static"
linker = "x86_64-linux-musl-gcc"
